[build]
  command = "echo 'No build required for Streamlit app'"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/*"
  to = "/app.py"
  status = 200

[context.production.environment]
  STREAMLIT_SERVER_PORT = "8501"
  STREAMLIT_SERVER_ADDRESS = "0.0.0.0"
